### ISSUE TITLE
Output image is empty

### ISSUE THREAD

**Issue by Wolfos** [nobuyukinyuu/tile-extruder#1]
It just outputs an empty image. Are there any requirements in image format or size? Using PNG and an NPOT sheet.

**Comment by nobuyukinyuu** [comment]
Hello,

What are the arguments you are specifying at the command line? It would be
helpful if you gave the exact input.  The tokenizer doesn't do a whole lot
of sanitizing, so you should specify parameters as they are shown in the
help menu.

**Comment by Wolfos** [comment]
TileExtruder Input.png -pad 1 -space 0 -size 32 Output.png

But now it crashes. I'll have a go at debugging it.

**Comment by Wolfos** [comment]
Hm, it runs with the debugger attached but crashes if I call it from a command line, even with -h

**Comment by nobuyukinyuu** [comment]
Try this line instead:

`TileExtruder Input.png pad=1 space=0 size=32 Output.png`

**Comment by nobuyukinyuu** [comment]
Sorry, ignore the backticks, that was meant to create an inline quote.

Let me know if changing the syntax works so I may close the issue.

**Comment by Wolfos** [comment]
It's still crashing.

2016-03-11 22:35 GMT+01:00 Nobuyuki notifications@github.com:

**Comment by nobuyukinyuu** [comment]
I have tested it on one of my own images, and it appears to be working fine.  Here is the example image:

![tiles](https://cloud.githubusercontent.com/assets/1023003/13716492/015b7e14-e7a1-11e5-9ad3-995487b434b2.png)

And here is the line I used:
`TileExtruder.exe tiles.png size=16 pad=1 space=0 output.png`

Please check your syntax.  If you're still having a problem, let me know what the error message it throws when it crashes.

**Comment by nobuyukinyuu** [comment]
I just noticed you mentioned it running with the debugger attached.  I was pretty certain I compiled it for release and the target was .net framework 3.0, however if it doesn't run at all then that could be indicative of another problem.  I'm afraid I don't know what that problem could be, but you could also try compiling from source using msbuild or any version of VS (including the express versions).  My apologies for the inconvenience.
